# ---------------------------
#  Supabase Local Config
# ---------------------------
project_id = "uxfcxllnzkdqgloevknd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "extensions"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
# pool_size was removed – Supabase CLI ≥ v1.160 manages this internally

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
# smtp_port / pop3_port can be added if needed

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

# ---------------------------
#  Edge Functions config
# ---------------------------
# Removed deprecated:
#   functions.enabled (bool)
#   [functions.serve] port = 54321

[functions]                     # table now used only for individual functions
# Example of per-function override:
# [functions.attempt-create]
# verify_jwt = true
