
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxfcxllnzkdqqloevknd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4ZmN4bGxuemtkcXFsb2V2a25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjgxOTYsImV4cCI6MjA2MjIwNDE5Nn0.-Rwz0flMEhoReKsOWSfudOOxDXA_J4_uU1FhZwI7BbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
